const USERSACHIEVEMENTS = (
  "USERSACHIEVEMENTS " +
  "(" +
  "ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY UNIQUE," +
  "userID INT," +
  "achievementID INT," +
  "updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
  "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
  "FOREIGN KEY (userID) REFERENCES USERS(ID)," +
  "FOREIGN KEY (achievementID) REFERENCES ACHIEVEMENTS(ID)" +
  ") ENGINE = InnoDB;"
);

module.exports = USERSACHIEVEMENTS;
